package user

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-ad.user.User",
		reflect.TypeOf((*User)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cannotChangePassword", GoGetter: "CannotChangePassword"},
			_jsii_.MemberProperty{JsiiProperty: "cannotChangePasswordInput", GoGetter: "CannotChangePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "city", GoGetter: "City"},
			_jsii_.MemberProperty{JsiiProperty: "cityInput", GoGetter: "CityInput"},
			_jsii_.MemberProperty{JsiiProperty: "company", GoGetter: "Company"},
			_jsii_.MemberProperty{JsiiProperty: "companyInput", GoGetter: "CompanyInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "container", GoGetter: "Container"},
			_jsii_.MemberProperty{JsiiProperty: "containerInput", GoGetter: "ContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "country", GoGetter: "Country"},
			_jsii_.MemberProperty{JsiiProperty: "countryInput", GoGetter: "CountryInput"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributes", GoGetter: "CustomAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributesInput", GoGetter: "CustomAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "department", GoGetter: "Department"},
			_jsii_.MemberProperty{JsiiProperty: "departmentInput", GoGetter: "DepartmentInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "displayName", GoGetter: "DisplayName"},
			_jsii_.MemberProperty{JsiiProperty: "displayNameInput", GoGetter: "DisplayNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "division", GoGetter: "Division"},
			_jsii_.MemberProperty{JsiiProperty: "divisionInput", GoGetter: "DivisionInput"},
			_jsii_.MemberProperty{JsiiProperty: "dn", GoGetter: "Dn"},
			_jsii_.MemberProperty{JsiiProperty: "emailAddress", GoGetter: "EmailAddress"},
			_jsii_.MemberProperty{JsiiProperty: "emailAddressInput", GoGetter: "EmailAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "employeeId", GoGetter: "EmployeeId"},
			_jsii_.MemberProperty{JsiiProperty: "employeeIdInput", GoGetter: "EmployeeIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "employeeNumber", GoGetter: "EmployeeNumber"},
			_jsii_.MemberProperty{JsiiProperty: "employeeNumberInput", GoGetter: "EmployeeNumberInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fax", GoGetter: "Fax"},
			_jsii_.MemberProperty{JsiiProperty: "faxInput", GoGetter: "FaxInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "givenName", GoGetter: "GivenName"},
			_jsii_.MemberProperty{JsiiProperty: "givenNameInput", GoGetter: "GivenNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "homeDirectory", GoGetter: "HomeDirectory"},
			_jsii_.MemberProperty{JsiiProperty: "homeDirectoryInput", GoGetter: "HomeDirectoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "homeDrive", GoGetter: "HomeDrive"},
			_jsii_.MemberProperty{JsiiProperty: "homeDriveInput", GoGetter: "HomeDriveInput"},
			_jsii_.MemberProperty{JsiiProperty: "homePage", GoGetter: "HomePage"},
			_jsii_.MemberProperty{JsiiProperty: "homePageInput", GoGetter: "HomePageInput"},
			_jsii_.MemberProperty{JsiiProperty: "homePhone", GoGetter: "HomePhone"},
			_jsii_.MemberProperty{JsiiProperty: "homePhoneInput", GoGetter: "HomePhoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "initialPassword", GoGetter: "InitialPassword"},
			_jsii_.MemberProperty{JsiiProperty: "initialPasswordInput", GoGetter: "InitialPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "initials", GoGetter: "Initials"},
			_jsii_.MemberProperty{JsiiProperty: "initialsInput", GoGetter: "InitialsInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "mobilePhone", GoGetter: "MobilePhone"},
			_jsii_.MemberProperty{JsiiProperty: "mobilePhoneInput", GoGetter: "MobilePhoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "office", GoGetter: "Office"},
			_jsii_.MemberProperty{JsiiProperty: "officeInput", GoGetter: "OfficeInput"},
			_jsii_.MemberProperty{JsiiProperty: "officePhone", GoGetter: "OfficePhone"},
			_jsii_.MemberProperty{JsiiProperty: "officePhoneInput", GoGetter: "OfficePhoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "organization", GoGetter: "Organization"},
			_jsii_.MemberProperty{JsiiProperty: "organizationInput", GoGetter: "OrganizationInput"},
			_jsii_.MemberProperty{JsiiProperty: "otherName", GoGetter: "OtherName"},
			_jsii_.MemberProperty{JsiiProperty: "otherNameInput", GoGetter: "OtherNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "passwordNeverExpires", GoGetter: "PasswordNeverExpires"},
			_jsii_.MemberProperty{JsiiProperty: "passwordNeverExpiresInput", GoGetter: "PasswordNeverExpiresInput"},
			_jsii_.MemberProperty{JsiiProperty: "poBox", GoGetter: "PoBox"},
			_jsii_.MemberProperty{JsiiProperty: "poBoxInput", GoGetter: "PoBoxInput"},
			_jsii_.MemberProperty{JsiiProperty: "postalCode", GoGetter: "PostalCode"},
			_jsii_.MemberProperty{JsiiProperty: "postalCodeInput", GoGetter: "PostalCodeInput"},
			_jsii_.MemberProperty{JsiiProperty: "principalName", GoGetter: "PrincipalName"},
			_jsii_.MemberProperty{JsiiProperty: "principalNameInput", GoGetter: "PrincipalNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetCannotChangePassword", GoMethod: "ResetCannotChangePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCity", GoMethod: "ResetCity"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompany", GoMethod: "ResetCompany"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainer", GoMethod: "ResetContainer"},
			_jsii_.MemberMethod{JsiiMethod: "resetCountry", GoMethod: "ResetCountry"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomAttributes", GoMethod: "ResetCustomAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetDepartment", GoMethod: "ResetDepartment"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDivision", GoMethod: "ResetDivision"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmailAddress", GoMethod: "ResetEmailAddress"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmployeeId", GoMethod: "ResetEmployeeId"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmployeeNumber", GoMethod: "ResetEmployeeNumber"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetFax", GoMethod: "ResetFax"},
			_jsii_.MemberMethod{JsiiMethod: "resetGivenName", GoMethod: "ResetGivenName"},
			_jsii_.MemberMethod{JsiiMethod: "resetHomeDirectory", GoMethod: "ResetHomeDirectory"},
			_jsii_.MemberMethod{JsiiMethod: "resetHomeDrive", GoMethod: "ResetHomeDrive"},
			_jsii_.MemberMethod{JsiiMethod: "resetHomePage", GoMethod: "ResetHomePage"},
			_jsii_.MemberMethod{JsiiMethod: "resetHomePhone", GoMethod: "ResetHomePhone"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitialPassword", GoMethod: "ResetInitialPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitials", GoMethod: "ResetInitials"},
			_jsii_.MemberMethod{JsiiMethod: "resetMobilePhone", GoMethod: "ResetMobilePhone"},
			_jsii_.MemberMethod{JsiiMethod: "resetOffice", GoMethod: "ResetOffice"},
			_jsii_.MemberMethod{JsiiMethod: "resetOfficePhone", GoMethod: "ResetOfficePhone"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrganization", GoMethod: "ResetOrganization"},
			_jsii_.MemberMethod{JsiiMethod: "resetOtherName", GoMethod: "ResetOtherName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPasswordNeverExpires", GoMethod: "ResetPasswordNeverExpires"},
			_jsii_.MemberMethod{JsiiMethod: "resetPoBox", GoMethod: "ResetPoBox"},
			_jsii_.MemberMethod{JsiiMethod: "resetPostalCode", GoMethod: "ResetPostalCode"},
			_jsii_.MemberMethod{JsiiMethod: "resetSmartCardLogonRequired", GoMethod: "ResetSmartCardLogonRequired"},
			_jsii_.MemberMethod{JsiiMethod: "resetState", GoMethod: "ResetState"},
			_jsii_.MemberMethod{JsiiMethod: "resetStreetAddress", GoMethod: "ResetStreetAddress"},
			_jsii_.MemberMethod{JsiiMethod: "resetSurname", GoMethod: "ResetSurname"},
			_jsii_.MemberMethod{JsiiMethod: "resetTitle", GoMethod: "ResetTitle"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrustedForDelegation", GoMethod: "ResetTrustedForDelegation"},
			_jsii_.MemberProperty{JsiiProperty: "samAccountName", GoGetter: "SamAccountName"},
			_jsii_.MemberProperty{JsiiProperty: "samAccountNameInput", GoGetter: "SamAccountNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "sid", GoGetter: "Sid"},
			_jsii_.MemberProperty{JsiiProperty: "smartCardLogonRequired", GoGetter: "SmartCardLogonRequired"},
			_jsii_.MemberProperty{JsiiProperty: "smartCardLogonRequiredInput", GoGetter: "SmartCardLogonRequiredInput"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberProperty{JsiiProperty: "stateInput", GoGetter: "StateInput"},
			_jsii_.MemberProperty{JsiiProperty: "streetAddress", GoGetter: "StreetAddress"},
			_jsii_.MemberProperty{JsiiProperty: "streetAddressInput", GoGetter: "StreetAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "surname", GoGetter: "Surname"},
			_jsii_.MemberProperty{JsiiProperty: "surnameInput", GoGetter: "SurnameInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "title", GoGetter: "Title"},
			_jsii_.MemberProperty{JsiiProperty: "titleInput", GoGetter: "TitleInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "trustedForDelegation", GoGetter: "TrustedForDelegation"},
			_jsii_.MemberProperty{JsiiProperty: "trustedForDelegationInput", GoGetter: "TrustedForDelegationInput"},
		},
		func() interface{} {
			j := jsiiProxy_User{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-ad.user.UserConfig",
		reflect.TypeOf((*UserConfig)(nil)).Elem(),
	)
}
